### ISSUE TITLE
Kineticist Elemental Blast is not shown

### ISSUE THREAD

**Issue by LTErnis** [this-gavagai/foundryvtt-tm#3]
Hey, noticed a few other small issues:

Kineticist's Elemental Blast is shown as an action but not a strike. The attack itself is automatically generated when Channel Elements is used and Effect: Kinetic Aura is applied.

![{E8537BDD-4177-4C88-A8A1-180E39333BB8}](https://github.com/user-attachments/assets/45584c26-323b-4320-90f8-8c8b50400af3)

Also, thanks for fixing the reaction spell icon :) However the issue still remains when clicking on the spell itself.

![{F88F2063-A264-4FE2-8668-C95ECF80D90D}](https://github.com/user-attachments/assets/b289ee9b-ae47-4914-aa3a-f0c88b2384ea)

Let me know if I should post a separate issue for each of these or a few at a time is fine (if I find any more), and thanks again!

**Comment by this-gavagai** [comment]
Thanks again!

The actions icon was an easy fix, and I've refactored the way I render icons so now hopefully other spots won't get missed. It should all work in the next alpha version.

Elemental Blast turns out to be pretty complicated! I've not yet played a kineticist, but the system handles them in a completely new way. This is going to take a bit of thinking, but I think I'll figure it out.

Glad to hear it's (mostly) working for you. Please do keep the issue reports coming, big or small. If it's not too inconvenient, separate issues for each thing is usually better.

**Comment by LTErnis** [comment]
The Elemental Blast also has other feats that modify it like Weapon Infusion, there might be others, but haven't looked deeper into Kineticist yet. Also, not sure if the intention is to let players select the damage type/traits of strikes same way as in the sheet since that might complicate it even more.

No problem, will split them up from now on :)

**Comment by this-gavagai** [comment]
Alrighty! I just pushed alpha-0028, which makes a first attempt at covering Elemental Blast. 

<img width="412" alt="Screenshot 2024-12-08 at 11 28 15 PM" src="https://github.com/user-attachments/assets/90a67840-5d21-4b7d-9207-caa9e9e53097">

A few caveats:
- It's not yet possible to choose damage types for the elements that give multiple options. I'll try to add this soon, as it's useful for regular strikes as well. (Same goes for choosing between 1- vs 2-action blasts.)
- Printing melee and ranged separately feels a bit cluttered, and my instinct is to use a toggle button instead. But, the original PF2e Foundry sheet prints them separately, so there may be a reason to keep it this way.
- Damage formula and modifier sets are not being printed on the info cards right now because I have to figure out how to get them from the system. This shouldn't affect the actual rolls; it just means that players won't be able to see this information in advance.
- Check modifiers sets are behaving strangely, too. Here, for example, the info window correctly shows Yoon with a +12 modifier, but the modifier list doesn't include the +1 bonus Yoon gets from the Gate Attenuator item so the numbers add up to only 11. Everything should still work correctly, but it's confusing.

Please take a look and let me know if anything is amiss. I don't have much understanding of Kineticist mechanics, so it's definitely possible I'm misunderstanding something basic.

**Comment by LTErnis** [comment]
Can confirm - works as you noted on my end. Not all of the modifiers are displayed but the end result is correct. 

The damage type selection is ignored when rolled from tablemate - it always rolls the default damage type (for example wood = bludgeoning) even though a different one is selected in the foundry sheet. Not even sure if that toggle is saved at all in the sheet somewhere? I understand it is not implemented yet but just wanted to note as it's a bit interesting :)

Regarding the display of melee and ranged separately - I guess it's just convention from all the other ranged/melee swappable attacks in both PCs and NPCs -

![{586114E1-FB7F-4281-93F9-91E70FAB963F}](https://github.com/user-attachments/assets/c80aef13-b271-4fac-a34e-683f95f66422)

Seems like a good start so far :) Will test it out more tomorrow during the game. Also, when I have the time, I'll probably look through most of the classes maybe will notice something else. Thanks!

**Comment by this-gavagai** [comment]
Good news! I've just pushed alpha-0028, which includes damage-type switching for both elemental blasts and versatile/modular strikes. It still needs proper testing, and I've noticed a few responsiveness issues, but it "should" be working alright.

I've still got to add single/double action blasts, but otherwise this one is getting close. Let me know how it works for you.

**Comment by LTErnis** [comment]
Looks great! Just checked it out for a bit before bed and wanted to update you so I don't forget - the damage button is not visible anymore but still works :)

**Comment by this-gavagai** [comment]
> the damage button is not visible anymore

This one was really causing me to scratch my head! Turns out it was a compiler issue, which is why it was showing up in the published version but not on my development/testing setup. I've fixed it now, I think, and I've also set a default gray color for buttons so that it will at least not be invisible if the rendering breaks again.

Anyway, let me know if you see anything else missing from Elemental Blasts. I'm still bugged by the incorrect modifiers, but I don't see a clean solution. It's not a deal-breaker, I don't think, but a bit annoying. Otherwise, I think it's just the 1/2 action selector left?

**Comment by this-gavagai** [comment]
1-action/2-action toggle has been added to elemental blasts. Foundry puts these on the top of the character sheet, but I thought the blast roll details was a better spot for it.

**Comment by LTErnis** [comment]
Great work! 😸 It is perfect now. 

It also got me thinking about other Roll Option toggles - the selector for actions is just a default Roll Option right? That's why it's at the top of the sheet. I'm wondering would it be possible to implement Roll Options in a generic way for all of them? I'll post a separate issue for this but that would be a big improvement!

**Comment by this-gavagai** [comment]
Great!

Yes, roll options are on the list. This one was a fairly specialized case, but it's given me a bit more confidence that implementing them generally will be possible and straightforward. I'll bump it up on the todo-list and continue discussion on the other issue. Thanks for all your help with the Elemental Blasts! If anything else related here comes up, let me know and I'll re-open this issue.
